import { DatePipe } from '@angular/common';
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { SelectModule } from 'primeng/select';
import { TableModule } from 'primeng/table';
import { TagModule } from 'primeng/tag';
import { TooltipModule } from 'primeng/tooltip';
import { TableLazyLoadEvent } from 'primeng/types/table';
import { Subject, debounceTime, distinctUntilChanged, finalize, forkJoin } from 'rxjs';
import { AuditAction, AuditEvent, AuditQuery, AuditService, AuditSummary } from '../../core/data/audit.service';
import { OrgDataService } from '../../core/data/org-data.service';
import { Role } from '../../core/models/enums';
import { AuthService } from '../../core/services/auth.service';

interface ChangeRow { field:string;before:string;after:string; }

@Component({selector:'app-audit-log',imports:[DatePipe,FormsModule,TableModule,SelectModule,InputTextModule,TagModule,ButtonModule,DialogModule,TooltipModule],template:`
<div class="oms-page">
  <div class="oms-page-header"><div><h1 class="oms-page-title">Audit Log</h1><p class="oms-page-subtitle">Investigate who changed what, when, and within which organization scope.</p></div>
    <div class="header-actions"><p-button label="Refresh" icon="pi pi-refresh" [outlined]="true" [loading]="loading()" (onClick)="refresh()" />
      <p-button label="Export CSV" icon="pi pi-download" [outlined]="true" [loading]="exporting()" (onClick)="exportCsv()" /></div></div>

  <div class="summary-grid">@for(card of cards();track card.label){<article class="summary-card"><i [class]="card.icon"></i><div><strong>{{card.value}}</strong><span>{{card.label}}</span></div></article>}</div>

  <div class="oms-surface-card">
    <p-table [value]="rows()" [loading]="loading()" [lazy]="true" [paginator]="true" [rows]="pageSize()" [rowsPerPageOptions]="[10,20,50,100]"
      [totalRecords]="totalRecords()" [first]="page()*pageSize()" (onLazyLoad)="onLazyLoad($event)" [sortField]="sortField()"
      [sortOrder]="sortDirection()==='asc'?1:-1" dataKey="id" [showCurrentPageReport]="true" currentPageReportTemplate="Showing {first}–{last} of {totalRecords}" styleClass="p-datatable-sm">
      <ng-template #caption><div class="filters">
        <span class="search"><i class="pi pi-search"></i><input pInputText type="search" [ngModel]="search()" (ngModelChange)="applySearch($event)" [ngModelOptions]="{standalone:true}" placeholder="Search user, username, email, action, module, or record ID…" /></span>
        @if(auth.isSuperAdmin()){<p-select [ngModel]="companyFilter()" (ngModelChange)="setCompany($event)" [ngModelOptions]="{standalone:true}" [options]="companyOptions()" optionLabel="label" optionValue="value" placeholder="All companies" />}
        <p-select [ngModel]="roleFilter()" (ngModelChange)="setRole($event)" [ngModelOptions]="{standalone:true}" [options]="roleOptions" optionLabel="label" optionValue="value" placeholder="All roles" />
        <p-select [ngModel]="actionFilter()" (ngModelChange)="setAction($event)" [ngModelOptions]="{standalone:true}" [options]="actionOptions" optionLabel="label" optionValue="value" placeholder="All actions" />
        <p-select [ngModel]="moduleFilter()" (ngModelChange)="setModule($event)" [ngModelOptions]="{standalone:true}" [options]="moduleOptions" placeholder="All modules" />
        <p-select [ngModel]="resultFilter()" (ngModelChange)="setResult($event)" [ngModelOptions]="{standalone:true}" [options]="resultOptions" optionLabel="label" optionValue="value" placeholder="All results" />
        <p-select [ngModel]="datePreset()" (ngModelChange)="setDatePreset($event)" [ngModelOptions]="{standalone:true}" [options]="dateOptions" optionLabel="label" optionValue="value" placeholder="Any date" />
        @if(datePreset()==='CUSTOM'){<label class="date-field">From<input pInputText type="date" [ngModel]="fromDate()" (ngModelChange)="setFrom($event)" [ngModelOptions]="{standalone:true}" /></label><label class="date-field">To<input pInputText type="date" [ngModel]="toDate()" (ngModelChange)="setTo($event)" [ngModelOptions]="{standalone:true}" /></label>}
        <button class="clear" type="button" [disabled]="!hasFilters()" (click)="clearFilters()"><i class="pi pi-filter-slash"></i> Clear</button>
      </div></ng-template>
      <ng-template #header><tr><th pSortableColumn="timestamp">Timestamp <p-sortIcon field="timestamp" /></th><th pSortableColumn="user">User <p-sortIcon field="user" /></th><th pSortableColumn="action">Action <p-sortIcon field="action" /></th><th pSortableColumn="module">Module <p-sortIcon field="module" /></th><th>Entity / record</th><th>Status</th><th>Details</th><th class="actions-col"></th></tr></ng-template>
      <ng-template #body let-event><tr><td><strong>{{event.timestamp|date:'medium'}}</strong><span class="secondary">{{event.timestamp|date:'z'}}</span></td>
        <td><strong>{{event.actorName}}</strong><span class="secondary">{{event.actorUsername}} · {{roleLabel(event.actorRole)}}</span></td>
        <td><p-tag [value]="actionLabel(event.action)" [severity]="actionSeverity(event.action)" /></td><td><span class="module"><i [class]="moduleIcon(event.module)"></i>{{event.module}}</span></td>
        <td><strong>{{event.entityType}}</strong><span class="secondary">{{event.entityId?'Record #'+event.entityId:'No record ID'}}</span></td><td><p-tag [value]="event.status" [severity]="event.status==='SUCCESS'?'success':'danger'" /></td>
        <td class="description">{{event.description}}</td><td><button class="icon-action" pTooltip="Inspect event" (click)="openDetails(event)"><i class="pi pi-eye"></i></button></td></tr></ng-template>
      <ng-template #emptymessage><tr><td colspan="8"><div class="empty" [class.error]="loadError()"><i class="pi" [class.pi-history]="!loadError()" [class.pi-exclamation-triangle]="loadError()"></i>
        <strong>{{loadError()?'Unable to load audit logs':'No audit events found'}}</strong><span>{{loadError()|| (hasFilters()?'No events match your current filters.':'Important system activity will appear here.') }}</span>
        @if(loadError()){<p-button label="Try again" icon="pi pi-refresh" [outlined]="true" (onClick)="refresh()" />}</div></td></tr></ng-template>
    </p-table>
  </div>

  <p-dialog [visible]="detailsVisible()" (visibleChange)="detailsVisible.set($event)" [modal]="true" [style]="{width:'50rem',maxWidth:'96vw'}" header="Audit event" [draggable]="false">
    @if(selected();as event){<div class="event-head"><span class="event-icon"><i [class]="moduleIcon(event.module)"></i></span><div><h2>{{actionLabel(event.action)}} {{event.entityType}}</h2><p>{{event.timestamp|date:'full'}}</p></div><p-tag [value]="event.status" [severity]="event.status==='SUCCESS'?'success':'danger'" /></div>
      <div class="detail-grid"><div><span>Performed by</span><strong>{{event.actorName}}</strong><small>{{event.actorUsername}} · {{event.actorEmail}}</small></div><div><span>Role</span><strong>{{roleLabel(event.actorRole)}}</strong></div>
        <div><span>Module</span><strong>{{event.module}}</strong></div><div><span>Action</span><strong>{{event.action}}</strong></div><div><span>Target</span><strong>{{event.entityType}}</strong></div><div><span>Record ID</span><strong>{{event.entityId||'Not available'}}</strong></div><div><span>Company ID</span><strong>{{event.companyId||'Global'}}</strong></div><div><span>Event ID</span><strong>#{{event.id}}</strong></div></div>
      <section class="description-panel"><h3>Description</h3><p>{{event.description}}</p></section>
      <section><h3>Before and after</h3>@if(changes(event).length){<div class="change-table"><div class="change-header"><strong>Field</strong><strong>Before</strong><strong>After</strong></div>@for(change of changes(event);track change.field){<div class="change-row"><strong>{{fieldLabel(change.field)}}</strong><span>{{change.before}}</span><span>{{change.after}}</span></div>}</div>}@else{<div class="no-changes">No structured before/after values were recorded for this event.</div>}</section>
      <div class="integrity"><i class="pi pi-lock"></i>This immutable event can be viewed and exported, but not edited or deleted.</div>
    }@else{<div class="empty"><i class="pi pi-spin pi-spinner"></i><strong>Loading audit event…</strong></div>}
  </p-dialog>
</div>`,styles:[`
.header-actions{display:flex;gap:.5rem}.summary-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:1rem;margin-bottom:1rem}.summary-card{display:flex;align-items:center;gap:.8rem;padding:1rem;border:1px solid var(--p-content-border-color);border-radius:12px;background:var(--p-content-background)}.summary-card>i{font-size:1.25rem;color:var(--p-primary-color)}.summary-card strong,.summary-card span{display:block}.summary-card strong{font-size:1.4rem}.summary-card span{font-size:.78rem;color:var(--p-text-muted-color)}
.filters{display:flex;flex-wrap:wrap;gap:.6rem;align-items:center}.search{position:relative;flex:1;min-width:21rem}.search i{position:absolute;left:.75rem;top:.8rem;color:var(--p-text-muted-color)}.search input{width:100%;padding-left:2.15rem}.date-field{display:grid;gap:.2rem;font-size:.7rem;color:var(--p-text-muted-color)}.clear,.icon-action{border:0;background:none;cursor:pointer;color:var(--p-primary-color)}.clear:disabled{opacity:.45}.secondary{display:block;font-size:.74rem;color:var(--p-text-muted-color);margin-top:.18rem}.module{display:flex;align-items:center;gap:.4rem}.description{max-width:22rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.actions-col{width:3rem}.empty{min-height:13rem;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:.65rem;color:var(--p-text-muted-color)}.empty>i{font-size:2rem}.empty.error>i{color:var(--p-red-500)}
.event-head{display:flex;align-items:center;gap:1rem}.event-head h2,.event-head p{margin:.15rem 0}.event-head p{color:var(--p-text-muted-color)}.event-head p-tag{margin-left:auto}.event-icon{width:48px;height:48px;border-radius:12px;display:grid;place-items:center;background:color-mix(in srgb,var(--p-primary-color) 12%,transparent);color:var(--p-primary-color);font-size:1.25rem}.detail-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin:1.5rem 0}.detail-grid span,.detail-grid strong,.detail-grid small{display:block}.detail-grid span{font-size:.7rem;text-transform:uppercase;color:var(--p-text-muted-color)}.detail-grid small{color:var(--p-text-muted-color)}section h3{font-size:.9rem;margin:1.2rem 0 .6rem}.description-panel,.no-changes,.integrity{padding:.85rem;border-radius:8px;background:var(--p-content-hover-background)}.description-panel p{margin:0;white-space:pre-wrap}.change-table{border:1px solid var(--p-content-border-color);border-radius:8px;overflow:hidden}.change-header,.change-row{display:grid;grid-template-columns:1fr 2fr 2fr;gap:1rem;padding:.65rem}.change-header{background:var(--p-content-hover-background)}.change-row+.change-row{border-top:1px solid var(--p-content-border-color)}.integrity{display:flex;gap:.5rem;margin-top:1rem;color:var(--p-text-muted-color);font-size:.8rem}
@media(max-width:900px){.summary-grid{grid-template-columns:repeat(2,1fr)}.detail-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.summary-grid,.detail-grid{grid-template-columns:1fr}.filters>*{flex:1 1 100%}.search{min-width:100%}.change-header,.change-row{grid-template-columns:1fr}.header-actions{width:100%;flex-wrap:wrap}}
` ]})
export class AuditLog implements OnInit{
  readonly auth=inject(AuthService);private readonly api=inject(AuditService);private readonly org=inject(OrgDataService);private readonly searchChanges=new Subject<string>();
  readonly rows=signal<AuditEvent[]>([]);readonly summary=signal<AuditSummary>({totalEvents:0,todayEvents:0,successfulActions:0,failedActions:0,securityEvents:0});readonly loading=signal(false);readonly exporting=signal(false);readonly loadError=signal<string|null>(null);
  readonly page=signal(0);readonly pageSize=signal(20);readonly totalRecords=signal(0);readonly sortField=signal<'timestamp'|'user'|'action'|'module'>('timestamp');readonly sortDirection=signal<'asc'|'desc'>('desc');readonly search=signal('');
  readonly companyFilter=signal<number|null>(null);readonly roleFilter=signal<Role|null>(null);readonly actionFilter=signal<AuditAction|null>(null);readonly moduleFilter=signal<string|null>(null);readonly resultFilter=signal<'SUCCESS'|'FAILED'|null>(null);readonly datePreset=signal<string|null>('LAST_7');readonly fromDate=signal<string|null>(null);readonly toDate=signal<string|null>(null);
  readonly selected=signal<AuditEvent|null>(null);readonly detailsVisible=signal(false);readonly companyOptions=computed(()=>[{label:'All companies',value:null},...this.org.companyOptions()]);
  readonly roleOptions=Object.values(Role).map((r)=>({label:this.roleLabel(r),value:r}));readonly actionOptions:( {label:string;value:AuditAction}[])=[['Created','CREATE'],['Updated','UPDATE'],['Archived','DELETE'],['Restored','RESTORE'],['Transferred','TRANSFER'],['Hierarchy changed','REPARENT'],['Login','LOGIN'],['Login failed','LOGIN_FAILED'],['Password changed','PASSWORD_CHANGE'],['Password reset','PASSWORD_RESET'],['Imported','IMPORT']].map(([label,value])=>({label,value:value as AuditAction}));
  readonly moduleOptions=['Authentication','Users & Roles','Companies','Departments','Staff','Positions','Vacancies','Profile','Settings'];readonly resultOptions=[{label:'Successful',value:'SUCCESS'},{label:'Failed',value:'FAILED'}];readonly dateOptions=[{label:'Any date',value:null},{label:'Today',value:'TODAY'},{label:'Yesterday',value:'YESTERDAY'},{label:'Last 7 days',value:'LAST_7'},{label:'Last 30 days',value:'LAST_30'},{label:'Custom range',value:'CUSTOM'}];
  readonly cards=computed(()=>[{label:'Total events',value:this.summary().totalEvents,icon:'pi pi-list'},{label:"Today's events",value:this.summary().todayEvents,icon:'pi pi-calendar'},{label:'Successful actions',value:this.summary().successfulActions,icon:'pi pi-check-circle'},{label:'Failed actions',value:this.summary().failedActions,icon:'pi pi-times-circle'},{label:'Security events',value:this.summary().securityEvents,icon:'pi pi-shield'}]);readonly hasFilters=computed(()=>!!(this.search().trim()||this.companyFilter()!=null||this.roleFilter()!=null||this.actionFilter()!=null||this.moduleFilter()!=null||this.resultFilter()!=null||this.datePreset()!=null));
  constructor(){this.searchChanges.pipe(debounceTime(350),distinctUntilChanged(),takeUntilDestroyed()).subscribe(()=>this.resetAndLoad())}
  ngOnInit(){if(!this.auth.isSuperAdmin())this.companyFilter.set(this.auth.currentUser()?.companyId??null);this.load()}
  onLazyLoad(e:TableLazyLoadEvent){const size=e.rows??this.pageSize();this.pageSize.set(size);this.page.set(Math.floor((e.first??0)/size));const field=typeof e.sortField==='string'?e.sortField:'timestamp';this.sortField.set((['timestamp','user','action','module'].includes(field)?field:'timestamp') as 'timestamp'|'user'|'action'|'module');this.sortDirection.set(e.sortOrder===1?'asc':'desc');this.load()}
  applySearch(v:string){this.search.set(v);this.searchChanges.next(v.trim())}setCompany(v:number|null){this.companyFilter.set(v);this.resetAndLoad()}setRole(v:Role|null){this.roleFilter.set(v);this.resetAndLoad()}setAction(v:AuditAction|null){this.actionFilter.set(v);this.resetAndLoad()}setModule(v:string|null){this.moduleFilter.set(v);this.resetAndLoad()}setResult(v:'SUCCESS'|'FAILED'|null){this.resultFilter.set(v);this.resetAndLoad()}
  setDatePreset(v:string|null){this.datePreset.set(v);if(v!=='CUSTOM'){this.fromDate.set(null);this.toDate.set(null)}this.resetAndLoad()}setFrom(v:string|null){this.fromDate.set(v||null);this.resetAndLoad()}setTo(v:string|null){this.toDate.set(v||null);this.resetAndLoad()}
  clearFilters(){this.search.set('');if(this.auth.isSuperAdmin())this.companyFilter.set(null);this.roleFilter.set(null);this.actionFilter.set(null);this.moduleFilter.set(null);this.resultFilter.set(null);this.datePreset.set(null);this.fromDate.set(null);this.toDate.set(null);this.resetAndLoad()}refresh(){this.load()}
  openDetails(e:AuditEvent){this.selected.set(null);this.detailsVisible.set(true);this.api.get(e.id).subscribe({next:(x)=>this.selected.set(x),error:()=>this.detailsVisible.set(false)})}
  exportCsv(){this.exporting.set(true);this.api.export(this.query()).pipe(finalize(()=>this.exporting.set(false))).subscribe((blob)=>{const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`oms-audit-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)})}
  changes(e:AuditEvent):ChangeRow[]{const before=this.parse(e.beforeValue),after=this.parse(e.afterValue);return [...new Set([...Object.keys(before),...Object.keys(after)])].filter((key)=>before[key]!==after[key]).map((field)=>({field,before:before[field]??'—',after:after[field]??'—'}))}
  fieldLabel(v:string){return v.replace(/([A-Z])/g,' $1').replace(/^./,(c)=>c.toUpperCase())}roleLabel(v:Role){return v.split('_').map((x)=>x[0]+x.slice(1).toLowerCase()).join(' ')}actionLabel(v:AuditAction){return v.split('_').map((x)=>x[0]+x.slice(1).toLowerCase()).join(' ')}
  actionSeverity(v:AuditAction):'success'|'info'|'danger'|'warn'|'secondary'{return v==='CREATE'||v==='LOGIN'?'success':v==='DELETE'||v==='LOGIN_FAILED'?'danger':v==='UPDATE'||v==='TRANSFER'||v==='REPARENT'?'info':v==='PASSWORD_CHANGE'||v==='PASSWORD_RESET'?'warn':'secondary'}
  moduleIcon(v:string){if(v.includes('Auth'))return'pi pi-lock';if(v.includes('User'))return'pi pi-users';if(v.includes('Compan'))return'pi pi-building';if(v.includes('Department'))return'pi pi-sitemap';if(v==='Staff')return'pi pi-id-card';if(v.includes('Position'))return'pi pi-briefcase';if(v.includes('Vacanc'))return'pi pi-inbox';if(v.includes('Setting'))return'pi pi-cog';return'pi pi-history'}
  private parse(v:string|null){const out:Record<string,string>={};if(!v)return out;v.split(',').forEach((part)=>{const index=part.indexOf('=');if(index>0)out[part.slice(0,index).trim()]=part.slice(index+1).trim()});return out}
  private range(){const now=new Date();const start=new Date(now);const end=new Date(now);end.setHours(0,0,0,0);end.setDate(end.getDate()+1);switch(this.datePreset()){case'TODAY':start.setHours(0,0,0,0);break;case'YESTERDAY':end.setDate(end.getDate()-1);start.setTime(end.getTime());start.setDate(start.getDate()-1);break;case'LAST_7':start.setHours(0,0,0,0);start.setDate(start.getDate()-6);break;case'LAST_30':start.setHours(0,0,0,0);start.setDate(start.getDate()-29);break;case'CUSTOM':return{from:this.fromDate()?`${this.fromDate()}T00:00:00`:null,to:this.toDate()?this.nextDay(this.toDate()!):null};default:return{from:null,to:null}}return{from:this.localIso(start),to:this.localIso(end)}}
  private nextDay(v:string){const d=new Date(`${v}T00:00:00`);d.setDate(d.getDate()+1);return this.localIso(d)}private localIso(d:Date){const p=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`}
  private query():AuditQuery{const r=this.range();return{page:this.page(),size:this.pageSize(),sort:this.sortField(),direction:this.sortDirection(),search:this.search(),action:this.actionFilter(),module:this.moduleFilter(),role:this.roleFilter(),companyId:this.companyFilter(),result:this.resultFilter(),from:r.from,to:r.to}}
  private resetAndLoad(){this.page.set(0);this.load()}private load(){this.loading.set(true);this.loadError.set(null);const q=this.query();forkJoin({page:this.api.list(q),summary:this.api.summary(this.companyFilter())}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:(r)=>{this.rows.set(r.page.content);this.totalRecords.set(r.page.totalElements);this.summary.set(r.summary)},error:()=>{this.rows.set([]);this.totalRecords.set(0);this.loadError.set('Check your connection and try again.')}})}
}
